// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using music_time_manager.Persistence;

#nullable disable

namespace music_time_manager.Persistence.Migrations
{
    [DbContext(typeof(MusicTimeManagerDbContext))]
    [Migration("20260715210204_RemoveSurrogateIdFromJunctionTables")]
    partial class RemoveSurrogateIdFromJunctionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("music_time_manager.Persistence.Entities.SubtaskAssigneeEntity", b =>
                {
                    b.Property<Guid>("SubtaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SubtaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SubtaskAssignees");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.SubtaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.TaskAssigneeEntity", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskAssignees");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecreatedFromTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("RecreatedFromTaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.SubtaskAssigneeEntity", b =>
                {
                    b.HasOne("music_time_manager.Persistence.Entities.SubtaskEntity", "Subtask")
                        .WithMany("SubtaskAssignees")
                        .HasForeignKey("SubtaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("music_time_manager.Persistence.Entities.UserEntity", "User")
                        .WithMany("SubtaskAssignees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.SubtaskEntity", b =>
                {
                    b.HasOne("music_time_manager.Persistence.Entities.TaskEntity", "Task")
                        .WithMany("SubtaskEntities")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.TaskAssigneeEntity", b =>
                {
                    b.HasOne("music_time_manager.Persistence.Entities.TaskEntity", "Task")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("music_time_manager.Persistence.Entities.UserEntity", "User")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.TaskEntity", b =>
                {
                    b.HasOne("music_time_manager.Persistence.Entities.TaskEntity", "RecreatedFromTask")
                        .WithMany("RecreatedTasks")
                        .HasForeignKey("RecreatedFromTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecreatedFromTask");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.SubtaskEntity", b =>
                {
                    b.Navigation("SubtaskAssignees");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.TaskEntity", b =>
                {
                    b.Navigation("RecreatedTasks");

                    b.Navigation("SubtaskEntities");

                    b.Navigation("TaskAssignees");
                });

            modelBuilder.Entity("music_time_manager.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("SubtaskAssignees");

                    b.Navigation("TaskAssignees");
                });
#pragma warning restore 612, 618
        }
    }
}
