
import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode } from "react";
import { Link, NavLink, Outlet } from "react-router-dom";
import { CalendarDays, CheckSquare, ChevronDown, ListTodo, Plus, Search, Users } from "lucide-react";
import { cn } from "./lib";
import type { User } from "./types";
import { CreateTaskModal } from "./task-modals";

export function Button({ className, variant = "primary", icon, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost"; icon?: ReactNode }) {
  return <button className={cn("focus-ring inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2 text-sm font-medium transition", variant === "primary" && "bg-stone-900 text-white hover:bg-stone-700", variant === "secondary" && "border border-stone-300 bg-white text-stone-800 hover:bg-stone-50", variant === "ghost" && "text-stone-500 hover:bg-stone-100 hover:text-stone-950", className)} {...props}>{icon}{props.children}</button>;
}
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("max-w-full rounded-xl border border-stone-200 bg-white", className)} {...props} />; }
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("focus-ring w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-900 placeholder:text-stone-400", className)} {...props} />; }
const avatarColors = ["#d9e1ff", "#d8f3df", "#f6dfc7", "#eeddf5", "#d6eff0"];
export function Avatar({ user, size = "md" }: { user: User; size?: "sm" | "md" | "lg" }) { const s = { sm: "h-6 w-6 text-[10px]", md: "h-8 w-8 text-xs", lg: "h-12 w-12 text-base" }[size]; const color = avatarColors[Array.from(user.id).reduce((sum, char) => sum + char.charCodeAt(0), 0) % avatarColors.length]; return <div title={user.username ?? "Участник"} className={cn("grid shrink-0 place-items-center rounded-full font-semibold text-stone-700", s)} style={{ backgroundColor: color }}>{user.username?.[0]?.toUpperCase() ?? "?"}</div>; }
export function AvatarGroup({ users }: { users: User[] | null | undefined }) { return users?.length ? <div className="flex max-w-full overflow-hidden -space-x-1.5">{users.map(user => <Avatar key={user.id} user={user} size="sm" />)}</div> : null; }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight text-stone-950 sm:text-3xl">{title}</h1>{description && <p className="mt-1.5 text-sm text-stone-500">{description}</p>}</div>{action}</div>; }

const nav = [{ to: "/today", label: "Сегодня", icon: CalendarDays }, { to: "/tasks", label: "Все задачи", icon: ListTodo }, { to: "/team", label: "Команда", icon: Users }];
export function AppShell() { const openCreate = () => window.dispatchEvent(new Event("open-new-task")); const brandClass = "flex items-center gap-2.5 rounded-lg px-2 font-semibold tracking-tight transition-opacity hover:opacity-70"; return <><div className="min-h-screen max-w-full overflow-x-hidden bg-[#f7f7f5] text-stone-900"><aside className="fixed inset-y-0 left-0 z-20 hidden w-60 border-r border-stone-200 bg-white px-4 py-5 md:block"><Link to="/today" className={cn("mb-10", brandClass)}><div className="grid h-8 w-8 place-items-center rounded-lg bg-stone-900 text-white"><CheckSquare size={17} /></div><span>Задачи</span></Link><nav className="space-y-1">{nav.map(item => <NavLink key={item.to} to={item.to} className={({ isActive }) => cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition", isActive ? "bg-stone-100 font-medium text-stone-950" : "text-stone-500 hover:bg-stone-50 hover:text-stone-950")}><item.icon size={17} />{item.label}</NavLink>)}</nav></aside><main className="min-w-0 md:pl-60"><header className="sticky top-0 z-10 border-b border-stone-200 bg-[#f7f7f5]/95 px-4 py-3 backdrop-blur md:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><Link to="/today" className={cn("min-w-0 md:hidden", brandClass)}><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-stone-900 text-white"><CheckSquare size={16} /></div><span className="truncate">Задачи</span></Link><label className="hidden max-w-xs flex-1 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 py-2 text-stone-400 sm:flex"><Search size={16} /><input className="w-full border-0 bg-transparent text-sm outline-none placeholder:text-stone-400" /></label><Button className="shrink-0" onClick={openCreate} icon={<Plus size={16} />}>Новая задача</Button></div></header><div className="mx-auto max-w-6xl px-4 py-7 md:px-8"><div className="mb-5 grid grid-cols-3 gap-1 border-b border-stone-200 pb-3 md:hidden">{nav.map(item => <NavLink key={item.to} to={item.to} className={({ isActive }) => cn("flex min-w-0 items-center justify-center gap-1 rounded-md px-1 py-1.5 text-xs", isActive ? "bg-stone-200 text-stone-950" : "text-stone-500")}><item.icon className="shrink-0" size={14} /><span className="truncate">{item.label}</span></NavLink>)}</div><Outlet /></div></main></div><CreateTaskModal /></>; }
export function AuthShell({ title, children, footer }: { title: string; children: ReactNode; footer: ReactNode }) { return <main className="grid min-h-screen place-items-center bg-[#f7f7f5] px-4"><section className="w-full max-w-sm"><div className="mb-8 flex items-center justify-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-lg bg-stone-900 text-white"><CheckSquare size={18} /></div><span className="font-semibold tracking-tight">Задачи</span></div><Card className="p-6 sm:p-8"><h1 className="text-xl font-semibold text-stone-950">{title}</h1><div className="mt-6">{children}</div></Card><p className="mt-5 text-center text-sm text-stone-500">{footer}</p></section></main>; }
