import { type FormEvent, useEffect, useState } from "react";
import { X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { Avatar, Button, Card, Input } from "./components";
import { getApiErrorMessage } from "./api/client";
import { useCreateTaskMutation, useRecreateTaskMutation, useUsersQuery } from "./api/hooks";
import { cn } from "./lib";
import type { Task } from "./types";

function AssigneePicker({ value, onChange }: { value: string[]; onChange: (ids: string[]) => void }) {
  const users = useUsersQuery();
  return <fieldset><legend className="text-sm font-medium">Исполнители <span className="font-normal text-stone-400">необязательно</span></legend><div className="mt-2 flex flex-wrap gap-2">{users.isPending ? <span className="text-sm text-stone-500">Загрузка участников...</span> : users.data?.map(user => <label key={user.id} className={cn("flex cursor-pointer items-center gap-2 rounded-lg border px-2.5 py-1.5 text-sm", value.includes(user.id) ? "border-stone-900 bg-stone-100" : "border-stone-200")}><input className="sr-only" type="checkbox" checked={value.includes(user.id)} onChange={() => onChange(value.includes(user.id) ? value.filter(id => id !== user.id) : [...value, user.id])} /><Avatar user={user} size="sm" />{user.username}</label>)}</div></fieldset>;
}

export function CreateTaskModal() {
  const [open, setOpen] = useState(false); const create = useCreateTaskMutation();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dueDate, setDueDate] = useState(""); const [assigneeIds, setAssigneeIds] = useState<string[]>([]);
  useEffect(() => { const handler = () => setOpen(true); window.addEventListener("open-new-task", handler); return () => window.removeEventListener("open-new-task", handler); }, []);
  const close = () => setOpen(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await create.mutateAsync({ task: { title, description: description || undefined, dueDate: new Date(dueDate).toISOString() }, assigneeIds }); setTitle(""); setDescription(""); setDueDate(""); setAssigneeIds([]); close(); } catch {} };
  return <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-stone-950/20 p-4"><Card className="w-full max-w-lg p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Новая задача</h2><button onClick={close} className="rounded p-1 text-stone-500 hover:bg-stone-100"><X size={18} /></button></div><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-medium">Название<Input value={title} onChange={e => setTitle(e.target.value)} className="mt-1.5" maxLength={200} required /></label><label className="block text-sm font-medium">Описание <span className="font-normal text-stone-400">необязательно</span><textarea value={description} onChange={e => setDescription(e.target.value)} className="mt-1.5 min-h-20 w-full rounded-lg border border-stone-300 px-3 py-2.5 text-sm" maxLength={2000} /></label><label className="block text-sm font-medium">Срок<Input value={dueDate} onChange={e => setDueDate(e.target.value)} className="mt-1.5" type="datetime-local" required /></label><AssigneePicker value={assigneeIds} onChange={setAssigneeIds} />{create.isError && <p className="text-sm text-red-700">{getApiErrorMessage(create.error)}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Отмена</Button><Button disabled={create.isPending}>{create.isPending ? "Создаём..." : "Создать"}</Button></div></form></Card></motion.div>}</AnimatePresence>;
}

export function RecreateTaskModal({ task, onClose }: { task: Task | null; onClose: () => void }) {
  const recreate = useRecreateTaskMutation(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dueDate, setDueDate] = useState(""); const [assigneeIds, setAssigneeIds] = useState<string[]>([]);
  useEffect(() => { if (task) { setTitle(task.title ?? ""); setDescription(task.description ?? ""); setAssigneeIds(task.assignees?.map(user => user.id) ?? []); setDueDate(""); } }, [task]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!task || !dueDate) return; const originalAssigneeIds = task.assignees?.map(user => user.id) ?? []; const assigneesChanged = assigneeIds.length !== originalAssigneeIds.length || assigneeIds.some(id => !originalAssigneeIds.includes(id)); const body: { dueDate: string; title?: string; description?: string; assigneeIds?: string[] } = { dueDate: new Date(dueDate).toISOString() }; if (title !== (task.title ?? "")) body.title = title; if (description !== (task.description ?? "")) body.description = description; if (assigneesChanged) body.assigneeIds = assigneeIds; try { await recreate.mutateAsync({ id: task.id, body }); onClose(); } catch {} };
  return <AnimatePresence>{task && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-stone-950/20 p-4"><Card className="w-full max-w-lg p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Пересоздать задачу</h2><button onClick={onClose} className="rounded p-1 text-stone-500 hover:bg-stone-100"><X size={18} /></button></div><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-medium">Название<Input value={title} onChange={e => setTitle(e.target.value)} className="mt-1.5" /></label><label className="block text-sm font-medium">Описание<textarea value={description} onChange={e => setDescription(e.target.value)} className="mt-1.5 min-h-20 w-full rounded-lg border border-stone-300 px-3 py-2.5 text-sm" /></label><label className="block text-sm font-medium">Новый срок<Input value={dueDate} onChange={e => setDueDate(e.target.value)} className="mt-1.5" type="datetime-local" required /></label><AssigneePicker value={assigneeIds} onChange={setAssigneeIds} />{recreate.isError && <p className="text-sm text-red-700">{getApiErrorMessage(recreate.error)}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Отмена</Button><Button disabled={recreate.isPending}>{recreate.isPending ? "Пересоздаём..." : "Пересоздать"}</Button></div></form></Card></motion.div>}</AnimatePresence>;
}
