import { type FormEvent, useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Check, Clock3, Pencil, Plus, Trash2, X } from "lucide-react";
import { Avatar, AvatarGroup, Button, Card, Input } from "./components";
import { getApiErrorMessage } from "./api/client";
import { useAssignSubtaskUsersMutation, useAssignTaskUsersMutation, useCreateSubtaskMutation, useDeleteSubtaskMutation, useDeleteTaskMutation, useSubtaskStatusMutation, useTaskQuery, useUpdateSubtaskMutation, useUpdateTaskMutation, useUsersQuery } from "./api/hooks";
import { cn, dueLabel } from "./lib";
import type { Subtask, Task, TaskStatus, User } from "./types";

const statusText: Record<TaskStatus, string> = { ToDo: "К выполнению", InProgress: "В работе", Done: "Готово" };
const asInputDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); };
const fullDateLabel = (value: string) => new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

function UserPicker({ selected, onChange }: { selected: string[]; onChange: (ids: string[]) => void }) { const users = useUsersQuery(); return <div className="mt-2 flex flex-wrap gap-2">{users.isPending ? <span className="text-sm text-stone-500">Загрузка участников...</span> : users.data?.map(user => <label key={user.id} className={cn("flex cursor-pointer items-center gap-1.5 rounded-md border px-2 py-1 text-xs", selected.includes(user.id) ? "border-stone-900 bg-white" : "border-stone-200 bg-white")}><input className="sr-only" type="checkbox" checked={selected.includes(user.id)} onChange={() => onChange(selected.includes(user.id) ? selected.filter(id => id !== user.id) : [...selected, user.id])} /><Avatar user={user} size="sm" />{user.username}</label>)}</div>; }

function TaskAssignees({ task }: { task: Task }) { const assign = useAssignTaskUsersMutation(); const [open, setOpen] = useState(false); const [selected, setSelected] = useState(task.assignees?.map(user => user.id) ?? []); useEffect(() => setSelected(task.assignees?.map(user => user.id) ?? []), [task.id, task.assignees]); if (!open) return task.assignees?.length ? <div className="mt-2 flex flex-wrap gap-2">{task.assignees.map((user: User) => <div key={user.id} className="flex items-center gap-2 rounded-lg bg-stone-100 px-2 py-1.5 text-sm"><Avatar user={user} size="sm" />{user.username}</div>)}</div> : <div className="mt-2 flex items-center gap-3"><p className="text-sm text-stone-500">Исполнители не назначены.</p><Button className="px-2.5 py-1.5 text-xs" onClick={() => setOpen(true)}>Назначить</Button></div>; return <div className="mt-2 rounded-lg bg-stone-50 p-3"><UserPicker selected={selected} onChange={setSelected} />{assign.isError && <p className="mt-2 text-xs text-red-700">{getApiErrorMessage(assign.error)}</p>}<div className="mt-3 flex gap-2"><Button variant="secondary" className="px-2.5 py-1.5 text-xs" onClick={() => setOpen(false)}>Отмена</Button><Button className="px-2.5 py-1.5 text-xs" disabled={!selected.length || assign.isPending} onClick={() => assign.mutate({ id: task.id, userIds: selected }, { onSuccess: () => setOpen(false) })}>{assign.isPending ? "Сохраняем..." : "Сохранить"}</Button></div></div>; }

function SubtaskAssignees({ subtask, taskId }: { subtask: Subtask; taskId: string }) { const assign = useAssignSubtaskUsersMutation(); const [open, setOpen] = useState(false); const [selected, setSelected] = useState(subtask.assignees?.map(user => user.id) ?? []); useEffect(() => setSelected(subtask.assignees?.map(user => user.id) ?? []), [subtask.id, subtask.assignees]); return <>{!open ? <button onClick={() => setOpen(true)} className="text-xs text-stone-500 hover:text-stone-900">Исполнители</button> : <div className="mt-3 rounded-lg bg-stone-50 p-3"><UserPicker selected={selected} onChange={setSelected} />{assign.isError && <p className="mt-2 text-xs text-red-700">{getApiErrorMessage(assign.error)}</p>}<div className="mt-3 flex gap-2"><Button variant="secondary" className="px-2.5 py-1.5 text-xs" onClick={() => setOpen(false)}>Отмена</Button><Button className="px-2.5 py-1.5 text-xs" disabled={!selected.length || assign.isPending} onClick={() => assign.mutate({ id: subtask.id, taskId, userIds: selected }, { onSuccess: () => setOpen(false) })}>{assign.isPending ? "Сохраняем..." : "Сохранить"}</Button></div></div>}</>; }

function SubtaskRow({ subtask, taskId }: { subtask: Subtask; taskId: string }) { const status = useSubtaskStatusMutation(); const update = useUpdateSubtaskMutation(); const remove = useDeleteSubtaskMutation(); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(subtask.title ?? ""); useEffect(() => setTitle(subtask.title ?? ""), [subtask.title]); const action = subtask.status === "ToDo" ? { label: "Взяться за работу", value: "InProgress" as const } : subtask.status === "InProgress" ? { label: "Выполнить", value: "Done" as const } : null; const save = () => title.trim() !== (subtask.title ?? "") ? update.mutate({ id: subtask.id, taskId, title: title.trim() }, { onSuccess: () => setEditing(false) }) : setEditing(false); return <div className="rounded-lg border border-stone-200 px-3 py-3"><div className="flex items-center gap-3"><div className={cn("h-2 w-2 rounded-full", subtask.status === "Done" ? "bg-emerald-500" : subtask.status === "InProgress" ? "bg-amber-500" : "bg-stone-300")} />{editing ? <input autoFocus value={title} onChange={event => setTitle(event.target.value)} onKeyDown={event => event.key === "Enter" && save()} className="min-w-0 flex-1 rounded border border-stone-300 px-2 py-1 text-sm" /> : <p className={cn("min-w-0 flex-1 text-sm", subtask.status === "Done" && "text-stone-400 line-through")}>{subtask.title ?? "Без названия"}</p>}<button aria-label="Редактировать подзадачу" onClick={() => editing ? save() : setEditing(true)} className="rounded p-1.5 text-stone-500 hover:bg-stone-100"><Pencil size={15} /></button><button aria-label="Удалить подзадачу" onClick={() => window.confirm("Удалить подзадачу?") && remove.mutate({ id: subtask.id, taskId })} className="rounded p-1.5 text-stone-500 hover:bg-red-50 hover:text-red-700"><Trash2 size={15} /></button></div><div className="mt-2 flex flex-wrap items-center gap-3 pl-5 text-xs text-stone-500"><span>{statusText[subtask.status]}</span>{subtask.isOverdue && <span className="text-red-600">Просрочено</span>}{subtask.assignees?.length ? <AvatarGroup users={subtask.assignees} /> : null}{action ? <motion.button whileTap={{ scale: 0.96 }} transition={{ duration: 0.12 }} disabled={status.isPending} onClick={() => status.mutate({ id: subtask.id, taskId, status: action.value })} className="rounded-md border border-stone-300 px-2 py-1 font-medium text-stone-700 hover:bg-stone-100">{action.label}</motion.button> : <span className="inline-flex items-center gap-1 text-emerald-700"><Check size={13} />Выполнено</span>}</div><SubtaskAssignees subtask={subtask} taskId={taskId} />{update.isError && <p className="mt-2 text-xs text-red-700">{getApiErrorMessage(update.error)}</p>}{remove.isError && <p className="mt-2 text-xs text-red-700">{getApiErrorMessage(remove.error)}</p>}</div>; }

function Subtasks({ taskId, subtasks }: { taskId: string; subtasks: Subtask[] }) { const create = useCreateSubtaskMutation(); const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); if (title.trim()) create.mutate({ taskId, title: title.trim() }, { onSuccess: () => { setTitle(""); setOpen(false); } }); }; return <section className="border-t border-stone-200 pt-5"><h3 className="font-medium">Подзадачи</h3><div className="mt-3 space-y-2">{subtasks.length ? subtasks.map(subtask => <SubtaskRow key={subtask.id} subtask={subtask} taskId={taskId} />) : <div className="flex items-center gap-3"><p className="text-sm text-stone-500">Подзадач пока нет.</p><Button className="px-2.5 py-1.5 text-xs" onClick={() => setOpen(true)}>Добавить</Button></div>}</div>{open ? <form onSubmit={submit} className="mt-3 flex gap-2"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Новая подзадача" maxLength={200} autoFocus /><Button disabled={create.isPending} icon={<Plus size={15} />}>{create.isPending ? "Добавляем..." : "Добавить"}</Button></form> : subtasks.length ? <Button variant="secondary" className="mt-3 px-2.5 py-1.5 text-xs" onClick={() => setOpen(true)} icon={<Plus size={14} />}>Добавить подзадачу</Button> : null}{create.isError && <p className="mt-2 text-sm text-red-700">{getApiErrorMessage(create.error)}</p>}</section>; }

function EditTaskForm({ task, close, onDeleted }: { task: Task; close: () => void; onDeleted: () => void }) { const update = useUpdateTaskMutation(); const remove = useDeleteTaskMutation(); const [title, setTitle] = useState(task.title ?? ""); const [description, setDescription] = useState(task.description ?? ""); const [dueDate, setDueDate] = useState(asInputDate(task.dueDate)); const submit = (event: FormEvent) => { event.preventDefault(); const body: { title?: string; description?: string; dueDate?: string } = {}; if (title !== (task.title ?? "")) body.title = title; if (description !== (task.description ?? "")) body.description = description; if (dueDate !== asInputDate(task.dueDate)) body.dueDate = new Date(dueDate).toISOString(); if (!Object.keys(body).length) return close(); update.mutate({ id: task.id, body }, { onSuccess: close }); }; return <form onSubmit={submit} className="space-y-3"><label className="block text-sm font-medium">Название<Input className="mt-1.5" value={title} onChange={event => setTitle(event.target.value)} /></label><label className="block text-sm font-medium">Описание<textarea className="mt-1.5 min-h-20 w-full rounded-lg border border-stone-300 px-3 py-2.5 text-sm" value={description} onChange={event => setDescription(event.target.value)} /></label><label className="block text-sm font-medium">Срок<Input className="mt-1.5" type="datetime-local" value={dueDate} onChange={event => setDueDate(event.target.value)} /></label>{update.isError && <p className="text-sm text-red-700">{getApiErrorMessage(update.error)}</p>}{remove.isError && <p className="text-sm text-red-700">{getApiErrorMessage(remove.error)}</p>}<div className="flex items-center justify-between gap-2"><Button type="button" variant="ghost" className="hover:bg-red-50 hover:text-red-700" onClick={() => window.confirm("Удалить задачу и все её подзадачи?") && remove.mutate(task.id, { onSuccess: onDeleted })} disabled={remove.isPending} icon={<Trash2 size={15} />}>Удалить</Button><div className="flex gap-2"><Button type="button" variant="secondary" onClick={close}>Отмена</Button><Button disabled={update.isPending}>{update.isPending ? "Сохраняем..." : "Сохранить"}</Button></div></div></form>; }

export function TaskDetailsModal({ taskId, editInitially = false, onClose }: { taskId: string | null; editInitially?: boolean; onClose: () => void }) { const query = useTaskQuery(taskId); const [editing, setEditing] = useState(editInitially); useEffect(() => setEditing(editInitially), [taskId, editInitially]); const task = query.data; return <AnimatePresence>{taskId && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 overflow-y-auto bg-stone-950/20 p-4"><div className="grid min-h-full place-items-center"><Card className="w-full max-w-2xl p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Детали задачи</h2><button aria-label="Закрыть" onClick={onClose} className="rounded p-2 text-stone-500 hover:bg-stone-100"><X size={18} /></button></div>{query.isPending ? <p className="py-10 text-center text-sm text-stone-500">Загрузка...</p> : query.isError ? <p className="py-10 text-center text-sm text-red-700">{getApiErrorMessage(query.error)}</p> : task && <div className="mt-5">{editing ? <EditTaskForm task={task} close={() => setEditing(false)} onDeleted={onClose} /> : <><h3 className="text-xl font-semibold">{task.title ?? "Без названия"}</h3>{task.description && <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-stone-600">{task.description}</p>}<div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-stone-500">Срок: </span><Clock3 className="mr-1 inline" size={14} />{fullDateLabel(task.dueDate)}</p><p><span className="text-stone-500">Создано: </span>{fullDateLabel(task.createdAt)}</p><p><span className="text-stone-500">Статус: </span>{statusText[task.status]}</p><p>{task.isOverdue ? <span className="font-medium text-red-600">Просрочено</span> : <span className="text-emerald-700">Не просрочено</span>}</p></div><div className="mt-5 mb-6"><p className="text-sm font-medium">Исполнители</p><TaskAssignees task={task} /></div><Subtasks taskId={task.id} subtasks={task.subtasks ?? []} /></>}</div>}</Card></div></motion.div>}</AnimatePresence>; }
